global_frame: /map
robot_base_frame: /base_link
update_frequency: 4.0
publish_frequency: 1.0
transform_tolerance: 0.3
static_map: false
rolling_window: true
track_unknown_space: false
width: 15.0
height: 15.0
resolution: 0.10

footprint: [[0.2, -0.90], [0.2, 0.90], [-1.55, 0.0]]

plugins:
    -
        name: footprint_layer
        type: "costmap_2d::FootprintLayer"
    -
        name: obstacle_layer
        type: "costmap_2d::VoxelLayer"
    -
        name: inflation_layer
        type: "costmap_2d::InflationLayer"

obstacle_layer:
    origin_z: 0.10
    z_resolution: 0.10
    z_voxels: 16
    unknown_threshold: 8
    mark_threshold: 3
    #set if you want the voxel map published
    publish_voxel_map: true
    track_unknown_space: true

    observation_sources: port_point_cloud center_point_cloud starboard_point_cloud
    port_point_cloud: {
        topic: /cameras/navigation/port/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.10,
        max_obstacle_height: 0.5,
        obstacle_range: 15.0,
        raytrace_range: 16.0
        }
    center_point_cloud: {
        topic: /cameras/navigation/center/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.10,
        max_obstacle_height: 0.5,
        obstacle_range: 15.0,
        raytrace_range: 16.0
        }
    starboard_point_cloud: {
        topic: /cameras/navigation/starboard/points2,
        data_type: PointCloud2,
        expected_update_rate: 0.2,
        observation_persistence: 0.0,
        marking: true,
        clearing: true,
        min_obstacle_height: 0.10,
        max_obstacle_height: 0.5,
        obstacle_range: 15.0,
        raytrace_range: 16.0
        }

inflation_layer:
    cost_scaling_factor: 2.0
    inflation_radius: 5.0

